server/basket/urls.py
from django.urls import path, re_path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketGenericList.as_view(), name='list'),
    path('add/<int:pk>/', views.basket_add, name='add'),
    path('delete/<int:pk>/', views.BasketGenericDelete.as_view(), name='delete'),


]

server/server/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from products.endpoints.products import ProductViewSet


router = DefaultRouter()
router.register('products', ProductViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('products.urls.categories')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('api/', include(router.urls)),
    path('basket/', include('basket.urls', namespace='basket')),
    path('subd/', include('adminapp.urls', namespace='subd')),
    path('', include('products.urls.products')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/products/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=250,
        unique=True
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128
    )

    image = models.ForeignKey(
        'images.Image',
        on_delete=models.PROTECT,
    )

    snippet = models.TextField(
        verbose_name='описание',
        blank=True
    )

    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0
    )



    def __str__(self):
        return self.name

server/products/forms.py
from django import forms

from products.models import ProductCategory, Product

from images.models import Image


class CategoryForm(forms.Form):

    name = forms.CharField(
        label='title',
        widget=forms.widgets.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    description = forms.CharField(
        label='snippet',
        required=False,
        widget=forms.widgets.Textarea(
            attrs={'class': 'form-control'}
        )
    )


class ProductForm(forms.Form):

    name = forms.CharField(
        label='title',
        widget=forms.widgets.TextInput(
            attrs={'class': 'form-control'}
        )
    )

    category = forms.ModelChoiceField(
        queryset=ProductCategory.objects.all()
    )

    image = forms.ModelChoiceField(
        queryset=Image.objects.all()
    )

    snippet = forms.CharField(
        label='snippet',
        required=False,
        widget=forms.widgets.Textarea(
            attrs={'class': 'form-control'}
        )
    )

    cost = forms.DecimalField(
        label='cost',
        required=False,
        widget=forms.widgets.NumberInput(
            attrs={'class': 'form-control'}
        )
    )


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'image', 'snippet']

class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = ['name', 'description']

server/products/views/categories.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from products.models import ProductCategory, Product
from products.forms import CategoryModelForm
from basket.models import Basket
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

def index(request):
    return render(request, 'categories/list.html')

class CategoryGenericList(ListView):

    model = ProductCategory
    template_name = 'categories/list.html'
    context_object_name = 'items'

class CategoryGenericDetail(DetailView):

    model = ProductCategory
    template_name = 'categories/detail.html'
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        instance = context.get('object')
        context[self.context_object_name] = instance.product_set.all()
        return context

class CategoryGenericCreate(CreateView):

    model = ProductCategory
    form_class = CategoryModelForm
    template_name = 'products/create.html'
    success_url = reverse_lazy('products:list')

class CategoryGenericUpdate(UpdateView):

    model = ProductCategory
    form_class = CategoryModelForm
    template_name = 'products/create.html'
    success_url = reverse_lazy('products:list')

class CategoryGenericDelete(DeleteView):
    model = ProductCategory
    template_name = 'products/delete.html'
    success_url = reverse_lazy('products:list')

def category_create(request):

    success_url = reverse_lazy('products:list')

    form = CategoryModelForm(request.POST)

    if request.method == 'POST':

        if form.is_valid():

            form.save()

            return redirect(success_url)

    return render(request, 'products/create.html', {'form': form})

def category_list(request):
    title = 'категории'
    links_menu = ProductCategory.objects.all()
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        print(basket)

    products = Product.objects.all().order_by('name')
    context = {
        'title': title,
        'links_menu': links_menu,
        'items': products,
        'basket': basket,
    }
    return render(request, 'products/list.html', context)


def category_detail(request, pk):

    obj = {
    'instance': get_object_or_404(ProductCategory, id=pk),
    'items': Product.objects.filter(category=pk)
    }

    return render(request, 'products/category.html', obj)

server/products/views/products.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.urls import reverse_lazy
from products.models import ProductCategory, Product
from django.http import HttpResponse
from basket.models import Basket
from products.forms import ProductModelForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def products_pages(request, page=1):
    products = Product.objects.all()
    paginator = Paginator(products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': 'продукция',
        'links_menu': ProductCategory.objects.all(),
        'object_list': products_paginator
    }
    if request.user.is_authenticated:
        context['basket'] = Basket.objects.filter(user=request.user)

    return render(request, 'products/list.html', context)

class ProductGenericList(ListView):

    model = Product
    template_name = 'products/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['links_menu'] = ProductCategory.objects.all()
        if self.request.user.is_authenticated:
            context['basket'] = Basket.objects.filter(user=self.request.user)
        return context


class ProductGenericDetail(DetailView):

    model = Product
    template_name = 'products/detail.html'
    context_object_name = 'instance'



class ProductGenericCreate(CreateView):

    model = Product
    form_class = ProductModelForm
    template_name = 'products/create.html'
    success_url = reverse_lazy('products:list')

class ProductGenericUpdate(UpdateView):

    model = Product
    form_class = ProductModelForm
    template_name = 'products/create.html'
    success_url = reverse_lazy('products:list')

class ProductGenericDelete(DeleteView):
    model = Product
    template_name = 'products/delete.html'
    success_url = reverse_lazy('products:list')

def product_list(request):
    title = 'продукты'
    links_menu = ProductCategory.objects.all()
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        print(basket)

    products = Product.objects.all().order_by('name')
    context = {
        'title': title,
        'links_menu': links_menu,
        'items': products,
        'basket': basket,
    }
    return render(request, 'products/list.html', context)


def product_detail(request, pk):

    obj = {'instance': get_object_or_404(Product, id=pk)}

    return render(request, 'products/detail.html', obj)

def product_create(request):

    success_url = reverse_lazy('products:list')

    form = ProductModelForm(request.POST)

    if request.method == 'POST':

        if form.is_valid():

            form.save()

            return redirect(success_url)

    return render(request, 'products/create.html', {'form': form})


def product_update(request, pk):

    success_url = reverse_lazy('products:list')

    obj = get_object_or_404(Product, id=pk)

    form = ProductModelForm(instance=obj)

    if request.method == 'POST':

        form = ProductModelForm(
            request.POST,
            instance=obj
        )

        if form.is_valid():

            form.save()

            return redirect(success_url)

    return render(request, 'products/create.html', {'form': form})

server/products/templates/products/category.html
{% extends 'master.html' %}

{% block page_styles %}
{% include 'products/components/stylesheet.html' %}
{% endblock %}

{% block page_title %}
Каталог
{% endblock %}

{% block page_content %}
    <main class="p-2 flex-grow-1">
      <div class="container">
        <h3>{{ instance.name }}</h3>
        <div class="row">
          <div class="col">
            <img src="/media/{{ instance.image.value }}" class="img-fluid border" alt="">
          </div>
          <div class="col">
            <p>{{ instance.snippet }}</p>
          </div>
        </div>
        <div class="row">
          {% for itm in items %}
            <div class="col">
                {% include 'products/components/product.html' with product=itm %}
            </div>
          {% endfor %}
        </div>
      </div>
    </main>
{% endblock %}

server/products/templates/products/create.html
{% extends 'master.html' %}

{% block page_styles %}
{% include 'products/components/stylesheet.html' %}
{% endblock %}

{% block page_title %}
Создать
{% endblock %}

{% block page_content %}
<main class="p-2 flex-grow-1">
  <div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% for err in form.not_field_errors %}
            <div class="alert alert-danger" role="alert">
                <span>{{ err}}</span>
            </div>
        {% endfor %}

        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.name }}">
                {{ field.label }}
            </label>
            {{ field }}

            {% for err in field.errors %}
                <small class="form-text">{{ err }}</small>
            {% endfor %}

        </div>
        {% endfor %}
        <input type="submit" value="Submit">
    </form>
  </div>
</main>


{% endblock %}

server/products/templates/products/delete.html
{% extends 'master.html' %}

{% block page_styles %}
{% include 'products/components/stylesheet.html' %}
{% endblock %}

{% block page_title %}
Удалить
{% endblock %}

{% block page_content %}
<main class="p-2 flex-grow-1">
  <div class="container">
    <form method="POST">
        {% csrf_token %}

        <input type="submit" value="DELETE">

    </form>
  </div>
</main>


{% endblock %}

server/products/templates/products/detail.html
{% extends 'master.html' %}

{% block page_styles %}
{% include 'products/components/stylesheet.html' %}
{% endblock %}

{% block page_title %}
Каталог
{% endblock %}

{% block page_content %}
    <main class="p-2 flex-grow-1">
      <div class="container">
        <h3>{{ instance.name }}</h3>
        <div class="row">
          <div class="col">
            <img src="/media/{{ instance.image.value }}" class="img-fluid border" alt="">
          </div>
          <div class="col">
            <p>{{ instance.snippet }}</p>
          </div>
          <div class="col">
            <p>{{ instance.cost }}</p>
          </div>
          <div class="col">
            <a href="{% url 'basket:add' pk=instance.id %}">добавить в корзину</a>
          </div>
        </div>

      </div>
    </main>
{% endblock %}

server/products/templates/products/list.html
{% extends 'master.html' %}

{% block page_styles %}
{% include 'products/components/stylesheet.html' %}
{% endblock %}

{% block page_title %}
{{ title }}
{% endblock %}

{% block page_content %}
    <main class="p-2 flex-grow-1">
      <div class="container">
        <h3>Наша продукция</h3>
        <div class="row">
          {% for cat in links_menu %}
            <div class="col">
                {% include 'products/components/category.html' with category=cat %}
            </div>
          {% endfor %}
          <div class="col">
            <a href="{% url 'basket:list' %}">
              {% if basket %}
                {{ basket.0.total_cost|floatformat:0 }} руб
                {{ basket.0.total_quantity }} шт
              {% endif %}
            </a>
          </div>
        </div>
        <div class="row">
          {% for itm in object_list %}
            <div class="col">
                {% include 'products/components/product.html' with product=itm %}
            </div>
          {% endfor %}
        </div>
        <div class="row">
          <div class="col">
            {% if object_list.has_previous %}
            <a href="{% url 'products:list' object_list.previous_page_number%}">Previous</a>
            {% endif %}
          </div>
          <div class="col">
            <span class="current">
              Page {{ object_list.number }} из {{ object_list.paginator.num_pages }}
            </span>
          </div>
          <div class="col">
            {% if object_list.has_next %}
            <a href="{% url 'products:list' object_list.next_page_number%}">Next</a>
            {% endif %}
          </div>

        </div>
        <div class="row">
          <a href="{% url 'categories:create' %}">добавить категорию</a>
        </div>
        <div class="row">
          <a href="{% url 'products:create' %}">добавить продукт</a>
        </div>
      </div>
    </main>
{% endblock %}