server/adminapp/urls.py
from django.urls import path, include
from . import views
from django.urls import reverse_lazy
from products.views.products import (
    ProductGenericList, ProductGenericDetail,
    ProductGenericUpdate, ProductGenericDelete
)
from products.views.categories import (
    CategoryGenericCreate, CategoryGenericUpdate, CategoryGenericDelete,
    CategoryGenericList, CategoryGenericDetail,
)

app_name = 'subd'
products_success_url = reverse_lazy('subd:products')
categories_success_url = reverse_lazy('subd:categories')
urlpatterns = [
    path('products/',
        ProductGenericList.as_view(template_name='adminapp/products/list.html'),
        name='products'
    ),
    path('products/<int:pk>/',
        ProductGenericDetail.as_view(),
        name='product_detail'
    ),
    path('products/update/<int:pk>/',
        ProductGenericUpdate.as_view(success_url=products_success_url),
        name='product_update'
    ),
    path('products/delete/<int:pk>/',
        ProductGenericDelete.as_view(success_url=products_success_url),
        name='product_delete'
    ),
    path('categories/',
        CategoryGenericList.as_view(template_name='adminapp/categories/list.html'),
        name='categories'
    ),
    path('categories/<int:pk>/',
        CategoryGenericDetail.as_view(),
        name='category_detail'
    ),
    path('categories/update/<int:pk>/',
        CategoryGenericUpdate.as_view(success_url=categories_success_url),
        name='category_update'
    ),
    path('categories/delete/<int:pk>/',
        CategoryGenericDelete.as_view(success_url=categories_success_url),
        name='category_delete'
    ),
]

server/basket/urls.py
from django.urls import path, re_path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketGenericList.as_view(), name='list'),
    path('add/<int:pk>/', views.basket_add, name='add'),
    path('delete/<int:pk>/', views.BasketGenericDelete.as_view(), name='delete'),


]

server/server/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from products.endpoints.products import ProductViewSet


router = DefaultRouter()
router.register('products', ProductViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('products.urls.categories')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('api/', include(router.urls)),
    path('basket/', include('basket.urls', namespace='basket')),
    path('subd/', include('adminapp.urls', namespace='subd')),
    path('', include('products.urls.products')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/adminapp/models.py
from django.db import models

# Create your models here.

server/adminapp/views.py
from django.shortcuts import render

server/adminapp/templates/adminapp/categories/list.html
{% extends 'master.html' %}

{% block page_styles %}
{% include 'products/components/stylesheet.html' %}
{% endblock %}

{% block page_title %}
{{ title }}
{% endblock %}

{% block page_content %}
    <main class="p-2 flex-grow-1">
      <div class="container">
        <h3>Категории (admin)</h3>
        <div class="row">
          {% for itm in object_list %}
            <div class="col">
              <a href="{% url 'subd:category_detail' pk=itm.id %}">
                {{ itm|title|add:'...!' }}
              </a>
              <div class="">
                <a href="{% url 'subd:category_update' pk=itm.id %}">редактировать</a>
              </div>
              <div class="">
                <a href="{% url 'subd:category_delete' pk=itm.id %}">удалить</a>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </main>
{% endblock %}