server/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp
from .views import LoginView
app_name = 'auth'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit'),

]

server/basket/urls.py
from django.urls import path, re_path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketGenericList.as_view(), name='list'),
    path('add/<int:pk>/', views.basket_add, name='add'),
    path('delete/<int:pk>/', views.BasketGenericDelete.as_view(), name='delete'),


]

server/server/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from products.endpoints.products import ProductViewSet


router = DefaultRouter()
router.register('products', ProductViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('products.urls.categories')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('api/', include(router.urls)),
    path('basket/', include('basket.urls', namespace='basket')),
    path('subd/', include('adminapp.urls', namespace='subd')),
    path('', include('products.urls.products')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/server/templates/master.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% block page_styles %}
    {% endblock %}

    <title>
      {% block page_title %}
      {% endblock %}
    </title>
  </head>
  <body class="d-flex flex-column">
    <header class="p-2 flex-{grow|shrink}-0">
      <a class="float-left" href="index.html">
        <img src="img/logo.png" height="40" alt="">
      </a>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" href="#">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Каталог</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Контакты</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth:edit' %}">
              {{ user.first_name|default:'User' }}
            </a>
          </li>
        {% endif %}
        <li>
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'auth:logout' %}">Log Out</a>
          {% else %}
            <a class="nav-link" href="{% url 'auth:login' %}">Log In</a>
          {% endif %}
        </li>
      </ul>
    </header>
    <section>
      {% block page_content %}
      {% endblock %}

    </section>
    {% block page_js %}
    {% endblock %}
    <footer class="p-2 flex-{grow|shrink}-0">
      <div class="container">
        <div class="row">
          <div class="col text-center">
            <h3>Контакты</h3>
            <address>
              г.Сызрань, ул.Нефтяная, 2Б
              <br>
              <abbr title="Телефон">тел.:</abbr>
              +7(927)798-12-47
            </address>
          </div>
          <div class="col text-center">
            <h3>Документы</h3>
            <a href="docs/info.pdf" class="badge badge-light">
              <img src="img/pdf.png" width="38px" alt="">
              информационный бюллетень
            </a>
          </div>
          <div class="col text-center">
            <h3>Оставьте e-mail</h3>
            <form>
            <div class="form-group">
              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col text-center text-uppercase">
            &copy 2011-2018, ООО "АНКОМ"
          </div>
          <div class="col text-center">
            <a href="skype:desperate_accountant?call">
              <img src="img/skype.png" width="38px" alt="skype">
            </a>
          </div>
          <div class="col text-center text-uppercase">
            политика приватности
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>